### ISSUE TITLE
Database dependency?

### ISSUE THREAD

**Issue by sinisterkid** [behoyh/google-drive-ui#1]
I wasn't able to load the dev environment on my localhost. Is there a database dependency needed first? See console errors.

![CleanShot 2022-04-22 at 09 05 36@2x](https://user-images.githubusercontent.com/2514727/164746313-c992626a-81b9-4c21-8853-8ba46303af5c.png)

**Comment by behoyh** [comment]
Hi @sinisterkid, 

That's all scaffolding from the Remix template I used. You should be able to assign or remove the `DATABASE_URL` string. Prisma is a data provider that I don't use in this project.

I will try removing unused boilerplate code in an upcoming push.

**Comment by behoyh** [comment]
@sinisterkid The dependency to Prisma has been removed, feel free to run `npm run dev` after you've pulled latest.

**Comment by sinisterkid** [comment]
It works, thanks! Very helpful.
