### ISSUE TITLE
Duplicate images?

### ISSUE THREAD

**Issue by sinisterkid** [behoyh/google-drive-ui#2]
This may not be an issue, but do you know why I have a duplicate image for every image I upload? One is the original filename, for example: 1234.jpg. And there's an identical image with the "_o" extension in the filename: 1234_o.jpg

<img width="410" alt="CleanShot 2022-05-18 at 14 19 39@2x" src="https://user-images.githubusercontent.com/2514727/169148925-8918b278-af27-4bb0-8078-cfa98dbf102f.png">

**Comment by behoyh** [comment]
Hi @sinisterkid,

This seems to be intended upstream functionality, see forum.ghost.org/t/double-image-uploads/5384.

Looks like this can be disabled via config.

**Comment by sinisterkid** [comment]
Excellent, thanks @behoyh !
I also noticed that I have several images that are duplicated with the exact same filename. How is that possible?

Finally, a new unrelated discovery: I don't see all the images I've uploaded to my blog. I only see exactly 100 images. Is there a limit or cutoff in google-drive-ui?

**Comment by behoyh** [comment]
Google Drive does not store files by name, rather by an assigned unique id, folders are "virtual" meaning it's all just metadata attached to the file.

I believe I set the file limit to 1000. Nonetheless there is no paging system yet 😅, So I'll have to work on that.

**Comment by sinisterkid** [comment]
Thanks! Overall, a very nifty feature. It would be helpful to see a summary of total volume one day= "You have 200 images for a total of 3.2 GB"
