### ISSUE TITLE
Question around where to place this code and which json do we put the key in. 

### ISSUE THREAD

**Issue by xsparro** [behoyh/google-drive-ui#3]
sorry i'm a bit new with these adapters setup. i've managed to get the google cloud setup but i'm having trouble to use this UI script to gain visual of what's been stored. can you please help?

**Comment by behoyh** [comment]
Hello,

So I guess a few requirements are needed first

* git or git bash
* Node.js LTS
* npm > v7

from there (inside a terminal or cmd prompt):
run `git clone https://github.com/behoyh/google-drive-ui`, 
run `cd google-drive-ui`
run `npm install`,
run `npm run dev`

Finally in a web browser  you will take the key .json from the google cloud setup and paste in the box at [http://localhost:3000](http://localhost:3000) and click `Save`.
